#ifndef SYS_NETINET_IN_H
#define SYS_NETINET_IN_H

#define IPPROTO_IP		0
#define IPPROTO_HOPOPTS		0
#define IPPROTO_ICMP		1
#define IPPROTO_IGMP		2
#define IPPROTO_IPIP		4
#define IPPROTO_TCP		6
#define IPPROTO_EGP		8
#define IPPROTO_PUP		12
#define IPPROTO_UDP		17
#define IPPROTO_IDP		22
#define IPPROTO_TP		29
#define IPPROTO_DCCP		33
#define IPPROTO_IPV6		41
#define IPPROTO_ROUTING		43
#define IPPROTO_FRAGMENT	44
#define IPPROTO_RSVP		46
#define IPPROTO_GRE		47
#define IPPROTO_ESP		50
#define IPPROTO_AH		51
#define IPPROTO_ICMPV6		58
#define IPPROTO_NONE		59
#define IPPROTO_DSTOPTS		60
#define IPPROTO_MTP		92
#define IPPROTO_BEETPH		94
#define IPPROTO_ENCAP		98
#define IPPROTO_PIM		103
#define IPPROTO_COMP		108
#define IPPROTO_SCTP		132
#define IPPROTO_MH		135
#define IPPROTO_UDPLITE		136
#define IPPROTO_RAW		255
#define IPPROTO_MAX		256

#endif